Repository tibiadata/tibiadata-api-go, pull requests merged in 2022-01, with the labels that each got.

#16 Fix decoding decoding issues
  .github/workflows/build.yml
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: go

#10 Removing some code smell from SonarCloud
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/webserver.go
Labels: go

#17 Moving vocation logic to separate function
  src/TibiaHighscoresV3.go
  src/TibiaSpellsOverviewV3.go
  src/webserver.go
Labels: go

#18 clear lint errors
  src/TibiaHighscoresV3.go
  src/webserver.go
Labels: good first issue, go

#19 idiomatic go
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaFansitesV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: go

#20 Addition of two guild endpoints
  README.md
  src/TibiaCharactersCharacterV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/webserver.go
Labels: documentation, enhancement, go

#23 Added Tibia Char Bazaar Auction endpoint.
  src/TibiaCharbazaarAuctionV3.go
  src/webserver.go
Labels: enhancement, good first issue, go

#25 Adding proxy support to replace default URL
  src/webserver.go
Labels: go

#27 Removing duplicate function
  src/TibiaCharactersCharacterV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaSpellsOverviewV3.go
  src/webserver.go
Labels: go

#29 Refactor to use pure goquery and no manual regex.
  src/TibiaGuildsOverviewV3.go
Labels: go

#31 Enhance data collection and debugging information
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: go

#34 Maintenance mode detection with error message return
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: enhancement, go

#35 Guilds name upper casing correction
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
Labels: go

#36 Adding rate-limit detection and status code switching
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: go

#41 Adding SonarCloud code coverage analyzing
  .github/workflows/sonarcloud.yml
  README.md
  sonar-project.properties
Labels: github_actions

#40 Add unit tests for Character API, cache all Regex queries, move much of Character API to goquery DOM walking vs Regex
  go.mod
  go.sum
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
  testdata/characters/Borttagna Gubben.html
  testdata/characters/Darkside Rafa.html
  testdata/characters/Riley No Hands.html
  testdata/characters/Torbjörn.html
  testdata/characters/Zugspitze Housekeeper.html
Labels: go

#48 Adding codecov.io
  .github/workflows/codecov.yml
  README.md
Labels: github_actions

#49 Handle timezone information during DateTime parsing (#46)
  go.mod
  go.sum
  src/TibiaCharactersCharacterV3_test.go
  src/TibiaDataUtils.go
  src/TibiaDataUtils_test.go
  src/webserver.go
Labels: go

#51 Updating workflows
  .github/workflows/codecov.yml
Labels: github_actions

#52 clean up webserver.go
  src/TibiaDataUtils.go
  src/main.go
  src/webserver.go
Labels: go

#32 Feature: Tibia News endpoints
  README.md
  src/TibiaDataUtils.go
  src/TibiaNewsV3.go
  src/TibiaNewslistV3.go
  src/webserver.go
Labels: documentation, enhancement, go

#53 Worlds Overview unit tests
  src/TibiaDataUtils.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsOverviewV3_test.go
  testdata/worlds/worlds.html
Labels: go

#26 Feature: Tibia Houses endpoints
  README.md
  src/HousesMapping.go
  src/TibiaDataUtils.go
  src/TibiaHousesHouseV3.go
  src/TibiaHousesOverviewV3.go
  src/main.go
  src/webserver.go
Labels: documentation, enhancement, go

#64 Refactor gin server to reduce code duplication
  go.mod
  go.sum
  src/TibiaCharactersCharacterV3.go
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesOverviewV3.go
  src/TibiaFansitesV3.go
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsOverviewV3.go
  src/TibiaHighscoresV3.go
  src/TibiaHousesHouseV3.go
  src/TibiaHousesOverviewV3.go
  src/TibiaKillstatisticsV3.go
  src/TibiaNewsV3.go
  src/TibiaNewslistV3.go
  src/TibiaSpellsOverviewV3.go
  src/TibiaSpellsSpellV3.go
  src/TibiaWorldsOverviewV3.go
  src/TibiaWorldsWorldV3.go
  src/webserver.go
Labels: go

#67 Swagger documentation annotations
  .github/workflows/documentation.yml
  README.md
  src/main.go
  src/webserver.go
Labels: documentation, enhancement

#72 Add unit tests for House Overview and House APIs
  src/TibiaHousesHouseV3.go
  src/TibiaHousesHouseV3_test.go
  src/TibiaHousesOverviewV3.go
  src/TibiaHousesOverviewV3_test.go
  src/webserver.go
  testdata/houses/Premia/Edron/Cormaya10.html
  testdata/houses/Premia/Edron/Cormaya11.html
  testdata/houses/overview/AnticaThaisGuilds.html
  testdata/houses/overview/AnticaThaisHouses.html
  testdata/houses/overview/PremiaEdronGuilds.html
  testdata/houses/overview/PremiaEdronHouses.html
  testdata/houses/overview/PremiaFarmineGuilds.html
  testdata/houses/overview/PremiaFarmineHouses.html
Labels: go

#73 Adding gzip compression middleware
  go.mod
  go.sum
  src/webserver.go
Labels: go

#79 Switching to http status codes
  src/webserver.go
  src/webserver_test.go
Labels: go

#75 Cleanup of characters deathlist
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
Labels: go

#74 Adjustment of endpoint namings
  README.md
  src/webserver.go
Labels: documentation, enhancement, go
