Repository tibiadata/tibiadata-api-go, pull requests merged in 2022-07, with the labels that each got.

#144 Removing **v** in container image tag
  .github/workflows/build.yml
Labels: github_actions

#148 updating `go build` step in dockerfile
  Dockerfile
Labels: docker

#151 Fix parsing issue when guild description contains founded string
  src/TibiaGuildsGuildV3.go
Labels: go

#153 Expanded HighscoreCategory with new boss points
  src/HighscoreCategory.go
  src/HighscoreCategory_test.go
  src/TibiaHighscoresV3.go
  src/webserver.go
Labels: good first issue, go

#154 Adding proxy protocol support to replace default https
  src/main.go
Labels: go
