Repository tibiadata/tibiadata-api-go, pull requests merged in 2022-04, with the labels that each got.

#115 adding support for finished auctions
  src/TibiaHousesHouseV3_test.go
  src/TibiaHousesOverviewV3.go
  src/TibiaHousesOverviewV3_test.go
  testdata/houses/Premia/Edron/Cormaya9c.html
  testdata/houses/overview/PremiaEdronHouses.html
Labels: enhancement, go

#116 enhancing deaths parsing of characters
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
  testdata/characters/Riley No Hands.html
Labels: enhancement, go

#117 fixing characters missing marriage and some more tests
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
  testdata/characters/Borttagna Gubben.html
Labels: enhancement, go

#118 moving finished bool into auction struct
  src/TibiaHousesOverviewV3.go
  src/TibiaHousesOverviewV3_test.go
Labels: go

#121 trimming suffix on guild rank
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
Labels: go

#124 change go version in go.mod
  .github/workflows/codecov.yml
  .github/workflows/documentation.yml
  go.mod
  go.sum
Labels: good first issue, dependencies

#125 adjusting parsing of fansite page
  src/TibiaFansitesV3.go
  src/TibiaFansitesV3_test.go
  testdata/fansites/all.html
Labels: go
