Repository tibiadata/tibiadata-api-go, pull requests merged in 2023-07, with the labels that each got.

#235 Fix test for tibiaHighscores with page param
  src/webserver_test.go
Labels: bug, go

#233 Rewrite boostable bosses parser
  src/TibiaBoostableBossesOverview.go
  src/TibiaBoostableBossesOverview_test.go
  src/static/testdata/boostablebosses/boostablebosses.html
  src/validation/limits.go
  src/webserver.go
Labels: go

#229 TibiaCharactersCharacter: use switch case for containsCreaturesWithOf
  src/TibiaCharactersCharacter.go
Labels: go

#236 webserver: pass normalized creature race to TibiaCreaturesCreatureIm…
  src/webserver.go
Labels: enhancement, go

#227 TibiaCharactersCharacter: remove account badges regex
  src/TibiaCharactersCharacter.go
Labels: go

#225 TibiaCharactersCharacter: remove death regex
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
  src/TibiaDataUtils.go
Labels: go

#223 TibiaCharactersCharacter: remove title regex
  src/TibiaCharactersCharacter.go
Labels: go

#224 TibiaCharactersCharacter: remove summon regex
  src/TibiaCharactersCharacter.go
Labels: go

#226 TibiaCharactersCharacter: remove char info regex
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
  src/static/testdata/characters/Akura Aleus.html
Labels: go
