Repository tibiadata/tibiadata-api-go, pull requests merged in 2023-01, with the labels that each got.

#175 Fix issue parsing summon mana cost
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesCreatureV3_test.go
  testdata/creatures/creature/centipede.html
  testdata/creatures/creature/hunter.html
  testdata/creatures/creature/skunk.html
Labels: bug, good first issue, go

#178 fixing account badge parsing
  src/TibiaCharactersCharacterV3.go
  src/TibiaCharactersCharacterV3_test.go
  testdata/characters/Luminals.html
Labels: bug, enhancement, go

#180 fix guild date format
  src/TibiaGuildsGuildV3.go
  src/TibiaGuildsGuildV3_test.go
  src/TibiaGuildsOverviewV3_test.go
  testdata/guilds/guild/Elysium.html
  testdata/guilds/guild/Kotki Antica.html
  testdata/guilds/guild/Mercenarys.html
Labels: bug, go

#147 Feature: adding support for k8s health endpoints
  README.md
  go.mod
  go.sum
  src/HousesMapping.go
  src/main.go
  src/webserver.go
  src/webserver_test.go
Labels: enhancement, dependencies, go

#182 add parsing of healed by damage for creatures
  src/TibiaCreaturesCreatureV3.go
  src/TibiaCreaturesCreatureV3_test.go
  src/static/testdata/creatures/creature/lava lurkers.html
Labels: go

#183 replacing strings.Title with cases.Title
  src/TibiaDataUtils.go
  src/TibiaHighscoresV3.go
  src/webserver.go
Labels: go

#184 extend special creatures list for death parsing
  src/TibiaCharactersCharacterV3.go
Labels: bug, go

#186 adding new error ErrorMaintenanceMode
  src/validation/errors.go
  src/validation/validation_test.go
  src/webserver.go
Labels: enhancement, go
