Repository tibiadata/tibiadata-api-go, pull requests merged in 2023-10, with the labels that each got.

#261 update boostable bosses parsers to latest tibia's html
  src/TibiaBoostableBossesOverview.go
  src/TibiaBoostableBossesOverview_test.go
  src/static/testdata/boostablebosses/boostablebosses.html
  src/validation/limits.go
Labels: bug, go

#264 fix character title that contains Grade
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
  src/static/testdata/characters/Nocna Furia.html
Labels: bug, go

#265 fix character deaths where timestamp contains CEST
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
  src/static/testdata/characters/Orca Kaoksh.html
Labels: bug, go

#221 all: reduce heap allocations
  src/TibiaCharactersCharacter.go
  src/TibiaCreaturesCreature.go
  src/TibiaCreaturesOverview.go
  src/TibiaFansites.go
  src/TibiaGuildsGuild.go
  src/TibiaGuildsOverview.go
  src/TibiaHighscores.go
  src/TibiaHousesHouse.go
  src/TibiaHousesOverview.go
  src/TibiaKillstatistics.go
  src/TibiaNews.go
  src/TibiaNewslist.go
  src/TibiaSpellsOverview.go
  src/TibiaSpellsSpell.go
  src/TibiaWorldsOverview.go
  src/TibiaWorldsWorld.go
  src/main.go
  src/tibiamapping/tibiamapping.go
  src/validation/tibia.go
  src/validation/validation.go
  src/validation/validation_test.go
  src/webserver.go
Labels: go

#272 fix characters with too many deaths cause crash
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
  src/static/testdata/characters/Stalone Matador.html
Labels: bug, go

#275 fix max length of character name
  src/validation/limits.go
  src/validation/validation_test.go
Labels: bug, go

#276 Truncated deaths
  src/TIbiaDataDocsV3.go
  src/TibiaCharactersCharacter.go
  src/TibiaCharactersCharacter_test.go
Labels: go

#281 workflow setup go version by go.mod
  .github/workflows/codecov.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
Labels: github_actions

#288 fix shorter character names
  src/validation/limits.go
  src/validation/validation_test.go
Labels: bug, go
